version: "3"
services:
  eda:
    build: ./
    user: root
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8888:8888"
    command: jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --port=8888
