[tool.poetry]
name = "jupyterlab_docker"
version = "0.2.0"
description = "Environment JupyterLab Poetry docker-compose"

authors = ["imaima"]

[tool.poetry.dependencies]
python = "^3.11"

jupyterlab = "^3.5"
numpy = "^1.23"
pandas = "^1.5"
scikit-learn = "^1.2"
matplotlib = "^3.6"
seaborn = "^0.12"
japanize-matplotlib = "^1.1"
sympy = "^1.11"
pandas-datareader = "~0.10"

[tool.poetry.dev-dependencies]
pytest = "^5.4"
pytest-watch = "^4.2.0"

[build-system]
requires = ["poetry_core>=1.0.10"]
build-backend = "poetry.masonry.api"
