version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202107-02

jobs:
  build:
    executor:
      name: machine-executor

    steps:
      - checkout

      - run:
          name: Build Docker
          command: docker-compose build

      - run:
          name: Docker-compose up
          command: docker-compose up -d

      - run:
          name: Finish message
          command: echo "finish build."
